CREATE CACHED TABLE IF NOT EXISTS HFE_SYSTEM_PROPERTY (
	ID INT	AUTO_INCREMENT	NOT	NULL,
	KEY VARCHAR(255)	NOT NULL,
	VALUE	VARCHAR(255)	NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (KEY)
)

/
CREATE CACHED TABLE IF NOT EXISTS HFE_PUBLIC_DIRECTORY (
	ID	INT	AUTO_INCREMENT	NOT	NULL,
	FULL_PATH	VARCHAR(255)	NOT NULL,
	DISP_NAME	VARCHAR(20)	NOT NULL,
	DEFAULT_AUTH INT,
	PRIMARY KEY (ID),
	UNIQUE (FULL_PATH)
)

/
CREATE CACHED TABLE IF NOT EXISTS HFE_FILE_INFOMATION (
	PARENT_PATH  VARCHAR(255)	NOT NULL,
	FILE_NAME    VARCHAR(255)	NOT NULL,
	OWNER       VARCHAR(10),
	OWNER_GROUP       VARCHAR(10),
	DESCRIPTION VARCHAR(2000),
	PRIMARY KEY (PARENT_PATH, FILE_NAME)
)

/
CREATE CACHED TABLE IF NOT EXISTS HFE_USER (
	ID         INT	AUTO_INCREMENT	NOT	NULL,
	ACCOUNT    VARCHAR(255)	NOT NULL,
	PASSWORD   VARCHAR(255)	NOT NULL,
	PRIMARY KEY (ID)
)
